### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendRight' of undefined

### ISSUE THREAD

**Issue by zaker** [lsegal/atom-go-format#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [go-format](https://github.com/lsegal/atom-go-format) package, v1.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'appendRight' of undefined

```
At /C:/Users/zaker/.atom/packages/go-format/lib/go-format-status-view.coffee:36

TypeError: Cannot read property 'appendRight' of undefined
  at GoFormatStatusView.module.exports.GoFormatStatusView.attach (C:\Users\zaker\.atom\packages\go-format\lib\go-format-status-view.coffee:16:14)
  at C:\Users\zaker\.atom\packages\go-format\lib\go-format-status-view.coffee:12:21

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.12
data-atom, v0.4.0
go-format, v1.0.7
go-plus, v3.1.3
language-rust, v0.3.5
minimap, v4.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lsegal** [comment]
Use the great [go-plus](https://github.com/joefitzgerald/go-plus) instead!
