### ISSUE TITLE
Stylesheet deprecations

### ISSUE THREAD

**Issue by nixxquality** [lsegal/atom-go-format#12]
**Use the `atom-text-editor` tag instead of the `editor` class.**
In stylesheets\go-format.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.**
In stylesheets\go-format.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by lsegal** [comment]
Use the great [go-plus](https://github.com/joefitzgerald/go-plus) instead!
