### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fnouama** [lsegal/atom-go-format#16]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
GoFormatStatusView.attach (/Users/francknouama/.atom/packages/go-format/lib/go-format-status-view.coffee:15:21)
```

**Comment by lsegal** [comment]
Use the great [go-plus](https://github.com/joefitzgerald/go-plus) instead!
